export const GAME_CONFIG = {
  CANVAS_WIDTH: 800,
  CANVAS_HEIGHT: 200,
  GROUND_Y: 170,
  GRAVITY: 0.55,
  JUMP_FORCE: -11,
  DINO_X: 50,
  DINO_WIDTH: 44,
  DINO_HEIGHT: 47,
  BASE_SPEED: 5,
  SCORE_PER_FRAME: 0.15,
} as const;

export const SCORE_VALIDATION = {
  ASSUMED_FPS: 60,
  MAX_SCORE_PER_SECOND: 18,
  SCORE_GRACE: 10,
  MAX_GAME_DURATION_MS: 20 * 60 * 1000,
} as const;
